-- Generated by generate.sh from repos/ai_tools_config.lua.j2 — do not edit.
-- This file defines which AI CLI tools are enabled in the current config.

local M = {}

-- Enabled AI CLI tools (from config.json ai_tools section)
M.enabled_tools = {
  "gemini",
  "claude",
  "agent",
  "codex",
  "agy",
  "opencode",
  "kilocode",
}

-- Tool metadata for display
M.tool_info = {
  gemini = { cmd = "gemini", label = "gemini" },
  claude = { cmd = "claude", label = "claude" },
  agent  = { cmd = "agent", label = "agent (cursor cli)" },
  codex  = { cmd = "codex", label = "codex" },
  agy    = { cmd = "agy", label = "agy (antigravity)" },
  opencode = { cmd = "opencode", label = "opencode" },
  kilocode  = { cmd = "kilocode", label = "kilocode" },
}

-- Get list of enabled tools that are installed (executable in PATH)
function M.get_installed_enabled_tools()
  local installed = {}
  for _, tool_key in ipairs(M.enabled_tools) do
    local info = M.tool_info[tool_key]
    if info and vim.fn.executable(info.cmd) == 1 then
      table.insert(installed, info)
    end
  end
  return installed
end

-- Get all enabled tools (installed or not) for display
function M.get_enabled_tools()
  local tools = {}
  for _, tool_key in ipairs(M.enabled_tools) do
    local info = M.tool_info[tool_key]
    if info then
      table.insert(tools, info)
    end
  end
  return tools
end

return M
