local map = vim.keymap.set

local function find_agent_term()
  for _, opts in pairs(vim.g.nvchad_terms or {}) do
    if opts and opts.id == "agentTerm" then
      return opts
    end
  end
  return nil
end

local function in_agent_term()
  local term = find_agent_term()
  return term ~= nil and term.buf == vim.api.nvim_get_current_buf()
end

local function ensure_is_agent_marker()
  local marker = vim.fn.getcwd() .. "/.was_agent"
  if vim.fn.filereadable(marker) == 0 then
    local f = io.open(marker, "w")
    if f then f:close() end
    _G.register_warm_workspace()
  end
end

-- Load AI tools config (generated by generate.sh from config.json ai_tools section).
-- Used only for the config-driven default tool (ai_tools_config.default_tool);
-- the selectable list below is the full set of known AI CLIs so :AiSelect offers
-- every installed tool, not just the config-enabled ones.
local ai_tools_ok, ai_tools_config = pcall(require, "ai_tools_config")

-- All known agent CLI tools. :AiSelect shows whichever of these are installed
-- (detected on PATH), so you can pick any installed tool; the config only
-- decides the DEFAULT (via ai_tools_config.default_tool).
local AGENT_TOOLS = {
  { cmd = "gemini", label = "gemini" },
  { cmd = "claude", label = "claude" },
  { cmd = "agent", label = "agent (cursor cli)" },
  { cmd = "codex", label = "codex" },
  { cmd = "agy", label = "agy (antigravity)" },
  { cmd = "opencode", label = "opencode" },
  { cmd = "kilocode", label = "kilocode" },
}

local _agent_cli_tool = nil
local function get_agent_cli_tool()
  if _agent_cli_tool then return _agent_cli_tool end
  local cmd = "bash -c 'source ~/.aliases 2>/dev/null && kv agentclitool 2>/dev/null'"
  local raw = vim.fn.system(cmd)
  local tool = raw:gsub("%s+", "")
  if tool == "" then
    -- No kv override: fall back to the config-driven default priority
    -- (set directly in ai_tools_config.lua.j2) so the agent terminal works
    -- on first launch without needing :AiSelect.
    if ai_tools_ok and ai_tools_config and ai_tools_config.default_tool then
      tool = ai_tools_config.default_tool
    else
      tool = "claude"
    end
  end
  _agent_cli_tool = tool
  return tool
end

local function open_or_focus_agent_term()
  ensure_is_agent_marker()
  local term = find_agent_term()
  if term and vim.api.nvim_buf_is_valid(term.buf) then
    local win_id = vim.fn.bufwinid(term.buf)
    if win_id ~= -1 then
      vim.api.nvim_set_current_win(win_id)
      vim.cmd "startinsert"
    else
      require("nvchad.term").toggle { pos = "vsp", id = "agentTerm" }
    end
    return
  end

  local root = vim.fn.shellescape(vim.fn.getcwd())
  local hash = vim.fn.system("printf '%s' " .. root .. " | md5sum | cut -c1-8"):gsub("%s+", "")
  local session = "agent@" .. hash

  local function attach()
    require("nvchad.term").toggle { pos = "vsp", cmd = "env -u TMUX tmux attach -t " .. session, id = "agentTerm" }
  end

  -- The warm daemon may still be spinning up the agent@ session (started lazily
  -- by the shell / by nvim on VimEnter). Poll briefly so the FIRST <C-l> attaches
  -- to the pre-warmed tmux session. If it still isn't there (daemon slow or not
  -- running), create the session on the fly and attach -- <C-l> ALWAYS opens tmux,
  -- it never falls back to the bare CLI tool.
  local function try_open(attempt)
    vim.fn.system("tmux has-session -t " .. session .. " 2>/dev/null")
    if vim.v.shell_error == 0 then
      attach()
    elseif attempt > 0 then
      vim.defer_fn(function() try_open(attempt - 1) end, 150)
    else
      local tool = get_agent_cli_tool()
      vim.fn.system("tmux new-session -d -s " .. session .. " " .. vim.fn.shellescape(tool) .. " 2>/dev/null")
      attach()
    end
  end
  try_open(12) -- up to ~1.8s waiting for the pre-warmed session
end

local function send_to_agent(text)
  open_or_focus_agent_term()
  vim.schedule(function()
    local term = find_agent_term()
    if term and term.buf and vim.api.nvim_buf_is_valid(term.buf) then
      local job_id = vim.b[term.buf].terminal_job_id
      if job_id then
        vim.api.nvim_chan_send(job_id, text)
      end
    end
  end)
end

map("n", "<leader><C-l>", open_or_focus_agent_term, { desc = "Open/focus agent terminal" })

-- NOTE: <leader><C-l> removed from terminal mode because leader=<Space>
-- caused input delay. Use <C-x> to exit terminal mode, then <leader><C-l>.

map("t", "<C-l>", function()
  if in_agent_term() then
    require("nvchad.term").toggle { pos = "vsp", cmd = get_agent_cli_tool(), id = "agentTerm" }
  end
end, { desc = "Close agent terminal from inside" })

map("v", "<C-l>", function()
  local start_line = vim.fn.line "v"
  local end_line = vim.fn.line "."
  if start_line > end_line then
    start_line, end_line = end_line, start_line
  end
  local file = vim.fn.expand "%:."
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "x", false)
  send_to_agent("@" .. file .. ":" .. start_line .. "-" .. end_line .. " ")
end, { desc = "Send file section reference to agent terminal" })

map("n", "<C-S-l>", function()
  local file = vim.fn.expand "%:."
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "x", false)
  send_to_agent("@" .. file .. " ")
end, { desc = "Send file reference to agent terminal" })

-- Resolve which AGENT_TOOLS are installed using a single shell invocation so
-- tools in brew/nix/local paths not in nvim's inherited PATH are found too.
local function get_installed_tools()
  local cmds = {}
  for _, tool in ipairs(AGENT_TOOLS) do cmds[#cmds + 1] = tool.cmd end
  -- nvim runs a login but NON-interactive shell, which sources ~/.zprofile but
  -- not ~/.zshrc. Tools installed to ~/.local/bin (e.g. agy) and brew's env
  -- (e.g. opencode) are invisible to a plain `zsh -lc`, so prepend both before
  -- probing PATH rather than running an interactive shell (which would trigger
  -- ssh-add, tmux, etc).
  local script = table.concat({
    "export PATH=\"$HOME/.local/bin:$PATH\"",
    "for b in /home/linuxbrew/.linuxbrew/bin/brew /opt/homebrew/bin/brew /usr/local/bin/brew; do",
    "  [ -x \"$b\" ] && eval \"$(\"$b\" shellenv)\" && break",
    "done",
    "for c in " .. table.concat(cmds, " ") .. "; do command -v \"$c\" >/dev/null 2>&1 && echo \"$c\"; done",
  }, "\n")
  local shell = vim.env.SHELL or "zsh"
  local raw = vim.fn.system({ shell, "-lc", script })
  local found = {}
  for line in raw:gmatch("[^\n]+") do found[line] = true end
  local installed = {}
  for _, tool in ipairs(AGENT_TOOLS) do
    if found[tool.cmd] or vim.fn.executable(tool.cmd) == 1 then
      installed[#installed + 1] = tool
    end
  end
  return installed
end

local function reprewarm_agent_sessions()
  -- After :AiSelect changes `agentclitool`, the existing pre-warmed agent
  -- sessions still run the OLD tool. Kill them and nudge the warm daemon
  -- (SIGUSR1) so it recreates them via agent-warm.sh, which reads the new kv
  -- value. Best-effort: no-op when the daemon isn't running.
  vim.fn.system(
    "tmux list-sessions -F '#{session_name}' 2>/dev/null"
      .. " | grep -E '^(agent-|agent@)'"
      .. " | while read -r s; do tmux kill-session -t \"$s\" 2>/dev/null; done"
      .. " || true"
  )
  local pid = io.open("/tmp/tmux_warm_daemon.pid", "r")
  if pid then
    local daemon_pid = pid:read("*l")
    pid:close()
    if daemon_pid then
      os.execute("kill -USR1 " .. daemon_pid .. " 2>/dev/null")
    end
  end
end

local function select_agent_cli_tool()
  local installed = get_installed_tools()

  if #installed == 0 then
    vim.notify(
      "No agent CLI tools found in PATH (checked: " .. #AGENT_TOOLS .. " known tools)",
      vim.log.levels.WARN,
      { title = "AiSelect" }
    )
    return
  end

  local current = get_agent_cli_tool()
  vim.ui.select(installed, {
    prompt = "Select default agent CLI tool",
    format_item = function(tool)
      local mark = tool.cmd == current and " (current)" or ""
      return tool.label .. mark
    end,
  }, function(choice)
    if not choice then return end
    local cmd = "bash -c " .. vim.fn.shellescape("source ~/.aliases 2>/dev/null && kv-put agentclitool " .. vim.fn.shellescape(choice.cmd))
    local out = vim.fn.system(cmd)
    if vim.v.shell_error ~= 0 then
      vim.notify("kv-put failed: " .. out, vim.log.levels.ERROR, { title = "AiSelect" })
      return
    end
    _agent_cli_tool = choice.cmd
    -- Re-pre-warm so the daemon's agent sessions switch to the new tool.
    reprewarm_agent_sessions()
    vim.notify("Default agent CLI tool set to " .. choice.cmd .. " (pre-warmed updated)", vim.log.levels.INFO, { title = "AiSelect" })
  end)
end

-- Requested as `:ai-select`, but Vim user-command names cannot contain hyphens
-- or start lowercase, so it is exposed as `:AiSelect`.
vim.api.nvim_create_user_command("AiSelect", select_agent_cli_tool, {
  desc = "Select default agent CLI tool spawned by <C-l>",
})

map("t", "<C-n>", function()
  if not in_agent_term() then
    return vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-n>", true, false, true), "n", false)
  end
  local chan = vim.b.terminal_job_id
  if chan then
    vim.fn.chansend(chan, "/clear")
  end
end, { desc = "Clear agent conversation (new chat)" })
